// This is a placeholder for the generated Convex API
// In a real project, this file would be auto-generated by Convex

export const api = {
  brandVoice: {
    get: async () => ({}),
    create: async () => ({}),
    update: async () => ({}),
  },
  content: {
    get: async () => ({}),
    list: async () => [],
    create: async () => ({}),
    update: async () => ({}),
    delete: async () => ({}),
  },
  users: {
    get: async () => ({}),
    create: async () => ({}),
    update: async () => ({}),
  },
  onboarding: {
    get: async () => ({}),
    create: async () => ({}),
    update: async () => ({}),
  },
}

